name: Module CI/CD

on: 
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Get the version from 'module.json'
    - name: Get Version
      shell: bash
      id: get-version
      run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: VERSION_PATHHOLDER
        replace: ${{ steps.get-version.outputs.version }}

    # create a zip file with all files required by the module to add to the release
    - run: zip -r module.zip . -x '*.git*' "doc/*" "archive/*"
    
    # Create a release for this specific version
    - name: Create Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # set this to false if you want to prevent updating existing releases
        name: Release ${{ steps.get-version.outputs.version }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json,./module.zip'
        tag: ${{ steps.get-version.outputs.version }}
